{application, couchdbproxy,
 [{description, "couchdbproxy"},
  {vsn, "0.4"},
  {modules, [
    couchdbproxy,
    couchdbproxy_ui,
    couchdbproxy_app,
    couchdbproxy_sup,
    couchdbproxy_web,
    couchdbproxy_deps,
	  couchdbproxy_http,
	  couchdbproxy_revproxy,
	  couchdbproxy_machines,
	  couchdbproxy_routes,
	  couchdbproxy_listener,
	  couchdbproxy_util
  ]},
  {registered, [couchdbproxy_sup]},
  {mod, {couchdbproxy_app, []}},
  {applications, [kernel, stdlib, crypto, couchbeam]}]}.
